name: PHP CI with phpbench

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@latest

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

    - name: Install dependencies
      run: composer install

    - name: Run phpbench tests
      run: |
        vendor/bin/phpbench run --report=chart --retry-threshold=5 --output=build-artifact


    - name: Publish Chart Report to GitHub Docs
      run: |
        mkdir -p $GITHUB_WORKSPACE/docs
        mkdir -p $GITHUB_WORKSPACE/docs/reports
        cp -r $GITHUB_WORKSPACE/.phpbench/reports/index.html $GITHUB_WORKSPACE/docs/reports
        cp -r $GITHUB_WORKSPACE/visualisations/* $GITHUB_WORKSPACE/docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
