name: PHPStan and SonarCloud Analysis

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPStan analysis
        run: ./vendor/bin/phpstan analyze --level 9 src tests --no-progress --error-format=json > .phpstan/report.json

      - name: Upload PHPStan report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: phpstan-report
          path: .phpstan/report.json

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: phpstan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarCloud analysis
        run: sonar-scanner

