name: CI
 
on:
  - pull_request
  - push
  
jobs:
  tests:
      name: Tests
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
          
        - name: Setup PHP with Xdebug
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            coverage: xdebug
            
        - name: Install dependencies with composer
          run: composer update --no-ansi --no-interaction --no-progress
          
        - name: Run tests with phpunit/phpunit
          run: vendor/bin/phpunit --coverage-clover=coverage.xml

        - name: Run ls -al
          run: echo $GITHUB_WORKSPACE

        - name: Fix code coverage paths
          run: sed -i -e "s|$GITHUB_WORKSPACE|/github/workspace|g" coverage.xml
          
  phpstan:
      name: Phpstan
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        - uses: actions/checkout@v3
        - uses: php-actions/composer@v6
        - name: PHPStan
          run: echo $(vendor/bin/phpstan analyze --error-format=json) > .phpstan/report.json
        - name: Upload PHPStan report to GitHub
          uses: actions/upload-artifact@v2
          with:
            name: report
            path: .phpstan/report.json

          
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
